### ISSUE TITLE
SMP issues with client side calls.

### ISSUE THREAD

**Issue by Dominance** [halvors/ElectricityMeter#56]
I just remembered after a long time to report this. Dont have a crash report readily available. But it should be really easy to replicate. Just toss down a block on SMP.

**Comment by halvors** [comment]
Well, this works just fine for me. I'll need a crash log to debug this further.

**Comment by halvors** [comment]
Fixed in commit 633accf232ce04678d10c93d4888c0935b2cdd3b.

**Comment by halvors** [comment]
A release fixing this bug has been released. http://minecraft.curseforge.com/projects/electrometrics/files/2261827

**Comment by Dominance** [comment]
Thanks halvors! Going to add it into divergence now that it is fixed up!
